### ISSUE TITLE
latest _installRocks issues

### ISSUE THREAD

**Issue by mdurn** [mah0x211/lenv#1]
It looks like these flags may no longer exist on the latest ./configure executable for luarocks:
sysconfdir, with-lua-bin, with-lua-include

It ran for me without those but those however I was not able to use "make bootstrap". I ran "make" and "make install" instead but then had issues with the "command bin/luarocks path" section.

**Comment by giulianisanches** [comment]
Trying to help here :)

Looking at the configure file from luarocks [here](https://github.com/keplerproject/luarocks/blob/master/configure) the flags that you mention still exists.

I have installed right now Lua 5.3.2 and LuaJIT 2.0.4 and haven't found any issue.

**Comment by mdurn** [comment]
Thanks for taking a look. I tried it again recently and had no issues. I'm not sure how I was getting the issue before but I haven't been able to reproduce it so I'll go ahead and close this.
