### ISSUE TITLE
no lua_vers.txt

### ISSUE THREAD

**Issue by dwdcth** [mah0x211/lenv#4]
I follow your steps to install lenv.But when I run "lenv install 5.2",it says
"could not open /home/xxxx/.lenv/lua_vers.txt".
There is no "lua_vers.txt".

**Comment by mah0x211** [comment]
did you run a 'fetch' command before do it?

> you must run a fetch command at the first. that command will crawling the version files of Lua, LuaJIT and LuaRocks immediately.

**Comment by dwdcth** [comment]
Yes,it's ok,after run 'fetch' command.Thank you a lot!
