### ISSUE TITLE
custom luarocks version argument for install-lj/install

### ISSUE THREAD

**Issue by vitenbergd** [mah0x211/lenv#7]
Hello, @mah0x211, first of all thanks a lot for **lenv** - works like a charm for me. The only issue i've met was - some lua libraries failed to build with the latest luarocks distribution (AFAIK luaposix + luarocks 3.0.4) and install-lj/install always pick the latest luarocks:

https://github.com/mah0x211/lenv/blob/master/lenv#L206

It would be great to have a way to somehow specify luarocks version you want to be installed with lua.

Something like this:
https://github.com/vitenbergd/lenv/commit/f9b55c02d1179cbfc13763d65199314d9a5fbf53

Do you think it's a good idea?

**Comment by mah0x211** [comment]
@vitenbergd 
sorry for my late reply.

I want to add that good feature to lenv. ;)
but, if changing the order of command-line arguments, the backward compatibility will be broken.
so, how about changing the version argument format <lua_version> to <lua_version_number<:luarocks_version>?

```
lenv install <ver[:rver]> <opt...>     Download and install a <ver> of lua
                                       with a <rver> or 'latest' luarocks.
```

**e.g.**

installing lua `5.1.5` and luarocks `latest`

```
$ lenv install 5.1.5
```

installing lua `5.1.5` and luarocks `3.0.4`

```
$ lenv install 5.1.5:3.0.4
```

**Comment by dargueta** [comment]
`lenv` is now completely broken on LuaRocks 3.2.0 (see [here](https://github.com/luarocks/luarocks/issues/1069)) so this has another use case for it. If you use [`GetOpt::Long`](https://perldoc.pl/Getopt::Long#Getting-Started-with-Getopt::Long) for passing arguments you don't have to break compatibility at all.
