### ISSUE TITLE
Doesn't install 5.1 correctly.

### ISSUE THREAD

**Issue by Industrial** [mah0x211/lenv#9]
Hi!

When I try to install 5.1, I get this error.

https://gist.github.com/Industrial/175a2e00e3140979090e40023b695d6d

It seems that you need to provide a target platform with the make command for 5.1.

**Comment by Industrial** [comment]
I've tried different versions.
- 5.0.x NO
- 5.1.x NO
- 5.2.x NO
- 5.3.x NO
- 5.4.x YES

**Comment by Industrial** [comment]
oops wrong button >_>

**Comment by imolein** [comment]
Hi, it seems like you forgot to give the plattform argument:
```
Please do    
           make PLATFORM
```
If you run it like this it should work:
```
lenv install 5.1.5 linux
```
